import type { GameDSL } from './types';

export const SURVIVAL_FIXTURE: GameDSL = {
  schema_version: '1.0',
  metadata: {
    title: 'Neon Swarm Survival',
    genre: 'Top-Down Survival',
    description: 'Dodge relentless hunter drones and gather energy orbs to survive.',
    archetype: 'survival',
  },
  world: {
    width: 800,
    height: 600,
    gravity: 0,
    background_color: '#0a0b12',
    theme: 'neon',
  },
  player: {
    spawn_x: 400,
    spawn_y: 300,
    speed: 240,
    jump_power: 0,
    max_health: 100,
    width: 32,
    height: 32,
    color: '#00f0ff',
  },
  entities: [
    {
      id: 'drone_1',
      type: 'enemy',
      x: 100,
      y: 100,
      width: 24,
      height: 24,
      speed: 90,
      health: 20,
      behavior: 'chase',
      color: '#ff0055',
      points: 20,
    },
    {
      id: 'drone_2',
      type: 'enemy',
      x: 700,
      y: 100,
      width: 24,
      height: 24,
      speed: 80,
      health: 20,
      behavior: 'chase',
      color: '#ff0055',
      points: 20,
    },
    {
      id: 'drone_3',
      type: 'enemy',
      x: 400,
      y: 500,
      width: 24,
      height: 24,
      speed: 100,
      health: 20,
      behavior: 'chase',
      color: '#ff0055',
      points: 20,
    },
    {
      id: 'orb_1',
      type: 'collectible',
      x: 200,
      y: 200,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 25,
    },
    {
      id: 'orb_2',
      type: 'collectible',
      x: 600,
      y: 400,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 25,
    },
    {
      id: 'orb_3',
      type: 'collectible',
      x: 200,
      y: 450,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 25,
    },
    {
      id: 'orb_4',
      type: 'collectible',
      x: 600,
      y: 150,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 25,
    },
  ],
  rules: [
    {
      id: 'rule_collect',
      trigger: 'on_collect',
      action: 'add_score',
      params: { amount: 25 },
    },
    {
      id: 'rule_collide',
      trigger: 'on_collide_enemy',
      action: 'damage_player',
      params: { amount: 15 },
    },
  ],
  ui: {
    show_health: true,
    show_score: true,
    status_text: 'DODGE DRONES & COLLECT ALL ENERGY ORBS',
  },
};

export const SHOOTER_FIXTURE: GameDSL = {
  schema_version: '1.0',
  metadata: {
    title: 'Cyberpunk Drone Assault',
    genre: 'Top-Down Shooter',
    description: 'Eliminate incoming enemy patrol units using plasma cannons.',
    archetype: 'shooter',
  },
  world: {
    width: 800,
    height: 600,
    gravity: 0,
    background_color: '#080910',
    theme: 'cyberpunk',
  },
  player: {
    spawn_x: 400,
    spawn_y: 500,
    speed: 260,
    jump_power: 0,
    max_health: 100,
    width: 32,
    height: 32,
    color: '#00f0ff',
  },
  entities: [
    {
      id: 'patrol_1',
      type: 'enemy',
      x: 200,
      y: 150,
      width: 24,
      height: 24,
      speed: 120,
      health: 20,
      behavior: 'patrol',
      color: '#ff0055',
      points: 50,
    },
    {
      id: 'patrol_2',
      type: 'enemy',
      x: 600,
      y: 220,
      width: 24,
      height: 24,
      speed: 140,
      health: 20,
      behavior: 'patrol',
      color: '#ff0055',
      points: 50,
    },
    {
      id: 'patrol_3',
      type: 'enemy',
      x: 400,
      y: 100,
      width: 24,
      height: 24,
      speed: 100,
      health: 20,
      behavior: 'patrol',
      color: '#ff0055',
      points: 50,
    },
  ],
  rules: [
    {
      id: 'rule_damage',
      trigger: 'on_collide_enemy',
      action: 'damage_player',
      params: { amount: 20 },
    },
  ],
  ui: {
    show_health: true,
    show_score: true,
    status_text: 'SPACEBAR: FIRE PLASMA | WASD: MOVE',
  },
};

export const PLATFORMER_FIXTURE: GameDSL = {
  schema_version: '1.0',
  metadata: {
    title: 'Neon Beacon Jump',
    genre: '2D Platformer',
    description: 'Jump across suspended cyber ledges, dodge spike hazards, and reach the beacon.',
    archetype: 'platformer',
  },
  world: {
    width: 1200,
    height: 600,
    gravity: 900,
    background_color: '#070913',
    theme: 'neon',
  },
  player: {
    spawn_x: 100,
    spawn_y: 480,
    speed: 220,
    jump_power: 520,
    max_health: 100,
    width: 32,
    height: 32,
    color: '#00f0ff',
  },
  entities: [
    // Floor platforms
    {
      id: 'ground_1',
      type: 'platform',
      x: 150,
      y: 560,
      width: 300,
      height: 40,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#1e2238',
      points: 0,
    },
    {
      id: 'ground_2',
      type: 'platform',
      x: 750,
      y: 560,
      width: 350,
      height: 40,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#1e2238',
      points: 0,
    },
    // Mid platforms
    {
      id: 'plat_1',
      type: 'platform',
      x: 400,
      y: 450,
      width: 120,
      height: 24,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#1e2238',
      points: 0,
    },
    {
      id: 'plat_2',
      type: 'platform',
      x: 580,
      y: 350,
      width: 120,
      height: 24,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#1e2238',
      points: 0,
    },
    {
      id: 'plat_3',
      type: 'platform',
      x: 780,
      y: 280,
      width: 140,
      height: 24,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#1e2238',
      points: 0,
    },
    // Spikes in gap
    {
      id: 'hazard_spikes',
      type: 'hazard',
      x: 450,
      y: 580,
      width: 160,
      height: 24,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ff3300',
      points: 0,
    },
    // Collectibles
    {
      id: 'gem_1',
      type: 'collectible',
      x: 400,
      y: 400,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 50,
    },
    {
      id: 'gem_2',
      type: 'collectible',
      x: 580,
      y: 300,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 50,
    },
    // Goal Beacon
    {
      id: 'goal_exit',
      type: 'obstacle',
      x: 820,
      y: 220,
      width: 36,
      height: 48,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#00ffaa',
      points: 0,
    },
  ],
  rules: [
    {
      id: 'rule_collect',
      trigger: 'on_collect',
      action: 'add_score',
      params: { amount: 50 },
    },
    {
      id: 'rule_goal',
      trigger: 'on_reach_goal',
      action: 'win_game',
      params: { message: 'BEACON ACTIVATED!' },
    },
    {
      id: 'rule_hazard',
      trigger: 'on_collide_enemy',
      action: 'damage_player',
      params: { amount: 100 },
    },
  ],
  ui: {
    show_health: true,
    show_score: true,
    status_text: 'REACH THE EXIT BEACON | A/D: MOVE | SPACE: JUMP',
  },
};

export const COLLECTOR_FIXTURE: GameDSL = {
  schema_version: '1.0',
  metadata: {
    title: 'Cyber Grid Collector',
    genre: 'Grid Puzzle / Collector',
    description: 'Navigate the grid maze and collect all encrypted data shards.',
    archetype: 'collector',
  },
  world: {
    width: 800,
    height: 600,
    gravity: 0,
    background_color: '#060810',
    theme: 'minimal',
  },
  player: {
    spawn_x: 100,
    spawn_y: 100,
    speed: 200,
    jump_power: 0,
    max_health: 100,
    width: 28,
    height: 28,
    color: '#00f0ff',
  },
  entities: [
    {
      id: 'shard_1',
      type: 'collectible',
      x: 300,
      y: 100,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 30,
    },
    {
      id: 'shard_2',
      type: 'collectible',
      x: 500,
      y: 300,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 30,
    },
    {
      id: 'shard_3',
      type: 'collectible',
      x: 300,
      y: 450,
      width: 20,
      height: 20,
      speed: 0,
      health: 1,
      behavior: 'stationary',
      color: '#ffe600',
      points: 30,
    },
    {
      id: 'patrol_security',
      type: 'enemy',
      x: 400,
      y: 200,
      width: 24,
      height: 24,
      speed: 110,
      health: 20,
      behavior: 'patrol',
      color: '#ff0055',
      points: 0,
    },
  ],
  rules: [
    {
      id: 'rule_collect',
      trigger: 'on_collect',
      action: 'add_score',
      params: { amount: 30 },
    },
    {
      id: 'rule_collide',
      trigger: 'on_collide_enemy',
      action: 'damage_player',
      params: { amount: 25 },
    },
  ],
  ui: {
    show_health: true,
    show_score: true,
    status_text: 'COLLECT ALL 3 ENCRYPTED SHARDS',
  },
};
