import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import { PrototypeModal } from '../components/Shared/PrototypeModal';
import { ProjectDetailsModal } from '../components/Shared/ProjectDetailsModal';
import type { GameProject } from '../types';

const DashboardPage = () => {
  const { state, setPrompt, updateBuildParams } = useAppContext();
  const navigate = useNavigate();
  
  const [showPlayModal, setShowPlayModal] = useState(false);
  const [detailsProject, setDetailsProject] = useState<GameProject | null>(null);

  const handleModify = (game: GameProject) => {
    setPrompt(game.prompt);
    updateBuildParams(game.parameters);
    navigate('/build');
  };

  return (
    <div className="flex-1 flex flex-col gap-8">
      {/* Header */}
      <header className="flex flex-col gap-1 border-l-4 border-primary pl-4 py-1">
        <h1 className="font-display text-base md:text-2xl text-on-surface uppercase tracking-tight">MY_GAMES_DASHBOARD</h1>
        <p className="font-mono text-xs text-on-surface-variant uppercase">Your generated prototypes and saved discoveries.</p>
      </header>

      {/* ═══ GENERATED BY YOU ═══ */}
      <section className="flex flex-col gap-4">
        <div className="flex items-center gap-2 border-b border-outline-variant pb-2">
          <span className="material-symbols-outlined text-secondary" style={{ fontVariationSettings: "'FILL' 1" }}>terminal</span>
          <h2 className="font-mono text-xs text-secondary uppercase tracking-widest">GENERATED BY YOU</h2>
        </div>

        {state.myGames.length === 0 ? (
          <div className="text-on-surface-variant font-mono text-xs border border-outline-variant bg-surface-container-low p-4 text-center">
            No games generated yet. Head to the Composer to build one!
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 stagger-enter stagger-1">
            {state.myGames.map((game, index) => (
              <div key={game.id} className={`bg-surface-container-low border border-primary/50 p-4 flex flex-col gap-4 relative overflow-hidden group hover:border-primary hover:-translate-y-1 hover:shadow-[0_0_20px_rgba(76,224,210,0.3)] transition-all duration-300 stagger-enter stagger-${(index % 5) + 1}`}>
                <div className="absolute top-0 right-0 p-2 opacity-10 font-mono text-[10px] pointer-events-none group-hover:opacity-20 transition-opacity">
                  SYS.ID: {game.id.substring(0,6).toUpperCase()}<br/>MEM_ADDR: 0x00FF
                </div>
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="font-display text-base md:text-lg text-primary uppercase truncate max-w-[200px]" title={game.title}>{game.title}</h3>
                    <div className="flex items-center gap-2 mt-1 flex-wrap">
                      <span className="font-mono text-[10px] text-outline border border-outline px-1">&gt; v1.0</span>
                      <span className="font-mono text-[10px] text-on-surface-variant">{game.genre}</span>
                      <span className="font-mono text-[10px] text-outline ml-4">Modified: {game.lastModified}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-1 bg-primary/10 border border-primary/30 px-2 py-1 shrink-0">
                    <div className="w-2 h-2 rounded-full bg-primary crt-flicker"></div>
                    <span className="font-mono text-[10px] text-primary uppercase">{game.status}</span>
                  </div>
                </div>

                <div className="h-32 w-full bg-surface-dim border border-outline-variant overflow-hidden relative flex items-center justify-center group-hover:brightness-110 transition-all">
                  <div className="absolute inset-0" style={{
                    backgroundImage: 'linear-gradient(rgba(76, 224, 210, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(76, 224, 210, 0.1) 1px, transparent 1px)',
                    backgroundSize: '20px 20px'
                  }}></div>
                  <span className="material-symbols-outlined text-4xl text-primary/30 relative z-10">videogame_asset</span>
                </div>

                <div className="flex gap-2 mt-auto">
                  <button onClick={() => setShowPlayModal(true)} className="flex-1 bg-primary text-on-primary font-mono text-xs py-2 uppercase shadow-[0_0_10px_rgba(76,224,210,0.2)] cursor-pointer btn-interactive energy-sweep glow-cyan">PLAY</button>
                  <button onClick={() => handleModify(game)} className="flex-1 border border-primary text-primary font-mono text-xs py-2 hover:bg-primary/10 uppercase cursor-pointer btn-interactive">MODIFY</button>
                  <button onClick={() => setDetailsProject(game)} className="flex-1 flex justify-center items-center gap-1 border border-outline-variant text-on-surface-variant font-mono text-xs hover:text-primary hover:border-primary uppercase cursor-pointer btn-interactive">
                    <span className="material-symbols-outlined text-[16px]">info</span> Details
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ═══ SAVED DISCOVERIES ═══ */}
      <section className="flex flex-col gap-4 mt-4">
        <div className="flex items-center gap-2 border-b border-outline-variant pb-2">
          <span className="material-symbols-outlined text-secondary" style={{ fontVariationSettings: "'FILL' 1" }}>bookmark</span>
          <h2 className="font-mono text-xs text-secondary uppercase tracking-widest">SAVED DISCOVERIES</h2>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 stagger-enter stagger-2">
          {state.savedDiscoveries.map((discovery, index) => (
            <div key={discovery.id} className={`bg-surface-container border-2 border-outline-variant flex flex-col relative overflow-hidden stagger-enter stagger-${(index % 5) + 1}`}>
              <div className={`h-4 bg-outline-variant w-full flex gap-1 px-2 items-center`}>
                <div className="w-1 h-1 bg-background rounded-full"></div>
                <div className="w-1 h-1 bg-background rounded-full"></div>
              </div>
              <div className="p-3 flex flex-col gap-2 h-full">
                <div className="flex justify-between items-center">
                  <span className={`font-mono text-[10px] text-${discovery.themeClass}`}>Match: {discovery.matchPercentage}%</span>
                  <span className="font-mono text-[10px] text-outline">Saved: {discovery.savedDate}</span>
                </div>
                <div className="aspect-video bg-surface-dim border border-outline-variant overflow-hidden flex items-center justify-center">
                  <span className={`material-symbols-outlined text-2xl text-${discovery.themeClass}/30`}>{discovery.icon}</span>
                </div>
                <h4 className="font-mono text-xs text-on-surface uppercase truncate mt-1">{discovery.title}</h4>
                <div className="flex justify-between items-center mt-auto">
                  <span className="font-mono text-[10px] text-outline">By {discovery.author}</span>
                  <div className={`w-2 h-2 rounded-full bg-${discovery.themeClass} ${discovery.themeClass === 'primary' ? 'crt-flicker shadow-[0_0_5px_rgba(76,224,210,0.8)]' : ''}`}></div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {showPlayModal && <PrototypeModal onClose={() => setShowPlayModal(false)} />}
      {detailsProject && <ProjectDetailsModal project={detailsProject} onClose={() => setDetailsProject(null)} />}
    </div>
  );
};

export default DashboardPage;
