import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import { PrototypeModal } from '../components/Shared/PrototypeModal';
import { ProjectDetailsModal } from '../components/Shared/ProjectDetailsModal';
import type { GameProject } from '../types';

const DashboardPage = () => {
  const { state, setPrompt, updateBuildParams, openAuthModal, removeSavedDiscovery, updateGameProject } = useAppContext();
  const navigate = useNavigate();

  const [selectedPlayProject, setSelectedPlayProject] = useState<GameProject | null>(null);
  const [detailsProject, setDetailsProject] = useState<GameProject | null>(null);

  const handleModify = (game: GameProject) => {
    setPrompt(game.prompt);
    updateBuildParams(game.parameters);
    navigate('/build');
  };

  return (
    <div className="flex-1 flex flex-col gap-8">
      {/* Header */}
      <header className="flex flex-col gap-1 border-l-4 border-primary pl-4 py-1">
        <h1 className="font-display text-base md:text-2xl text-on-surface uppercase tracking-tight">
          MY_GAMES_DASHBOARD
        </h1>
        <p className="font-mono text-xs text-on-surface-variant uppercase">
          Your generated prototypes and saved discoveries.
        </p>
      </header>

      {/* ═══ GENERATED BY YOU ═══ */}
      <section className="flex flex-col gap-4">
        <div className="flex items-center gap-2 border-b border-outline-variant pb-2">
          <span className="material-symbols-outlined text-secondary" style={{ fontVariationSettings: "'FILL' 1" }}>
            terminal
          </span>
          <h2 className="font-mono text-xs text-secondary uppercase tracking-widest">GENERATED BY YOU</h2>
        </div>

        {state.authStatus !== 'AUTHENTICATED' ? (
          <div className="text-on-surface-variant font-mono text-xs border border-outline-variant bg-surface-container-low p-8 text-center space-y-3">
            <p>You are browsing as an unauthenticated guest. Sign in to view and persist your generated games.</p>
            <button
              onClick={() => openAuthModal('login')}
              className="px-6 py-2.5 bg-primary text-on-primary font-mono text-xs uppercase rounded-sm btn-interactive glow-cyan cursor-pointer inline-flex items-center gap-2"
            >
              <span className="material-symbols-outlined text-sm">login</span>
              <span>Sign In to Access Projects</span>
            </button>
          </div>
        ) : state.isProjectsLoading ? (
          <div className="text-primary font-mono text-xs border border-primary/30 bg-surface-container-low p-6 text-center animate-pulse">
            &gt; SYNCING_BACKEND_PROJECTS...
          </div>
        ) : state.myGames.length === 0 ? (
          <div className="text-on-surface-variant font-mono text-xs border border-outline-variant bg-surface-container-low p-6 text-center">
            No games generated yet. Head to the Scene Composer to build one!
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 stagger-enter stagger-1">
            {state.myGames.map((game, index) => (
              <div
                key={game.id}
                className={`bg-surface-container-low border border-primary/50 p-4 flex flex-col gap-4 relative overflow-hidden group hover:border-primary hover:-translate-y-1 hover:shadow-[0_0_20px_rgba(76,224,210,0.3)] transition-all duration-300 stagger-enter stagger-${
                  (index % 5) + 1
                }`}
              >
                <div className="absolute top-0 right-0 p-2 opacity-10 font-mono text-[10px] pointer-events-none group-hover:opacity-20 transition-opacity">
                  SYS.ID: {game.id.substring(0, 6).toUpperCase()}
                  <br />
                  MEM_ADDR: 0x00FF
                </div>
                <div className="flex justify-between items-start">
                  <div>
                    <h3
                      className="font-display text-base md:text-lg text-primary uppercase truncate max-w-[200px]"
                      title={game.title}
                    >
                      {game.title}
                    </h3>
                    <div className="flex items-center gap-2 mt-1 flex-wrap">
                      <span className="font-mono text-[10px] text-outline border border-outline px-1">
                        {/* FS-026 fix: use real project version from currentVersion field */}
                        &gt; v{game.currentVersion ?? 1}.0
                      </span>
                      <span className="font-mono text-[10px] text-on-surface-variant">{game.genre}</span>
                      <span className="font-mono text-[10px] text-outline ml-4">Modified: {game.lastModified}</span>
                    </div>
                  </div>
                  <div
                    className={`flex items-center gap-1 border px-2 py-1 shrink-0 ${
                      game.status === 'ERROR'
                        ? 'bg-error/10 border-error/40'
                        : game.status === 'COMPILING'
                        ? 'bg-tertiary/10 border-tertiary/40'
                        : 'bg-primary/10 border-primary/30'
                    }`}
                  >
                    <div
                      className={`w-2 h-2 rounded-full ${
                        game.status === 'ERROR'
                          ? 'bg-error ai-pulse'
                          : game.status === 'COMPILING'
                          ? 'bg-tertiary ai-pulse'
                          : 'bg-primary'
                      }`}
                    ></div>
                    <span
                      className={`font-mono text-[10px] uppercase ${
                        game.status === 'ERROR' ? 'text-error' : game.status === 'COMPILING' ? 'text-tertiary' : 'text-primary'
                      }`}
                    >
                      {game.status}
                    </span>
                  </div>
                </div>

                <div className="h-32 w-full bg-surface-dim border border-outline-variant overflow-hidden relative flex items-center justify-center group-hover:brightness-110 transition-all">
                  <div
                    className="absolute inset-0"
                    style={{
                      backgroundImage:
                        'linear-gradient(rgba(76, 224, 210, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(76, 224, 210, 0.1) 1px, transparent 1px)',
                      backgroundSize: '20px 20px',
                    }}
                  ></div>
                  <span className="material-symbols-outlined text-4xl text-primary/30 relative z-10">
                    videogame_asset
                  </span>
                </div>

                <div className="flex gap-2 mt-auto">
                  <button
                    onClick={() => setSelectedPlayProject(game)}
                    className="flex-1 bg-primary text-on-primary font-mono text-xs py-2 uppercase shadow-[0_0_10px_rgba(76,224,210,0.2)] cursor-pointer btn-interactive energy-sweep glow-cyan"
                  >
                    PLAY
                  </button>
                  <button
                    onClick={() => handleModify(game)}
                    className="flex-1 border border-primary text-primary font-mono text-xs py-2 hover:bg-primary/10 uppercase cursor-pointer btn-interactive"
                  >
                    MODIFY
                  </button>
                  <button
                    onClick={() => setDetailsProject(game)}
                    className="flex-1 flex justify-center items-center gap-1 border border-outline-variant text-on-surface-variant font-mono text-xs hover:text-primary hover:border-primary uppercase cursor-pointer btn-interactive"
                  >
                    <span className="material-symbols-outlined text-[16px]">info</span> Details
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ═══ SAVED DISCOVERIES ═══ */}
      <section className="flex flex-col gap-4 mt-4">
        <div className="flex items-center gap-2 border-b border-outline-variant pb-2">
          <span className="material-symbols-outlined text-secondary" style={{ fontVariationSettings: "'FILL' 1" }}>
            bookmark
          </span>
          <h2 className="font-mono text-xs text-secondary uppercase tracking-widest">SAVED DISCOVERIES</h2>
        </div>

        {state.authStatus !== 'AUTHENTICATED' ? (
          <div className="text-on-surface-variant font-mono text-xs border border-outline-variant bg-surface-container-low p-6 text-center">
            Sign in to view your bookmarked Steam catalog discoveries.
          </div>
        ) : state.isSavedDiscoveriesLoading ? (
          <div className="text-primary font-mono text-xs border border-primary/30 bg-surface-container-low p-6 text-center animate-pulse">
            &gt; LOADING_SAVED_DISCOVERIES...
          </div>
        ) : state.savedDiscoveries.length === 0 ? (
          <div className="text-on-surface-variant font-mono text-xs border border-outline-variant bg-surface-container-low p-6 text-center">
            No saved discoveries yet. Bookmark interesting games found on the Discover page!
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 stagger-enter stagger-2">
            {state.savedDiscoveries.map((discovery, index) => (
              <div
                key={discovery.id}
                className={`bg-surface-container border-2 border-outline-variant flex flex-col relative overflow-hidden stagger-enter stagger-${
                  (index % 5) + 1
                } hover:border-secondary/50 transition-colors group`}
              >
                <div className="h-4 bg-outline-variant w-full flex justify-between px-2 items-center">
                  <div className="flex gap-1">
                    <div className="w-1 h-1 bg-background rounded-full"></div>
                    <div className="w-1 h-1 bg-background rounded-full"></div>
                  </div>
                  <button
                    onClick={() => removeSavedDiscovery(discovery.id)}
                    className="text-on-surface-variant hover:text-error text-[10px] font-mono cursor-pointer"
                    title="Delete bookmark"
                  >
                    ×
                  </button>
                </div>
                <div className="p-3 flex flex-col gap-2 h-full">
                  <div className="aspect-video bg-surface-dim border border-outline-variant overflow-hidden flex items-center justify-center">
                    <span className="material-symbols-outlined text-2xl text-secondary/40">
                      sports_esports
                    </span>
                  </div>
                  <h4 className="font-mono text-xs text-on-surface uppercase truncate mt-1 font-bold" title={discovery.title}>
                    {discovery.title}
                  </h4>
                  <div className="flex justify-between items-center mt-auto">
                    <span className="font-mono text-[10px] text-outline truncate max-w-[120px]">
                      {discovery.genres.slice(0, 2).join(', ') || 'Game'}
                    </span>
                    <div className="w-2 h-2 rounded-full bg-secondary"></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {selectedPlayProject && (
        <PrototypeModal
          project={selectedPlayProject}
          onClose={() => setSelectedPlayProject(null)}
          onProjectUpdated={updateGameProject}
        />
      )}
      {detailsProject && (
        <ProjectDetailsModal
          project={detailsProject}
          onClose={() => setDetailsProject(null)}
        />
      )}
    </div>
  );
};

export default DashboardPage;
