import React from 'react';
import { Link } from 'react-router-dom';

const DocumentationPage: React.FC = () => {
  return (
    <div className="w-full max-w-5xl mx-auto space-y-8 animate-fade-in pb-12">
      {/* Page Header */}
      <header className="border-b border-primary/30 pb-6 space-y-2">
        <div className="flex items-center gap-2 text-primary">
          <span className="material-symbols-outlined text-2xl">menu_book</span>
          <span className="font-mono text-xs uppercase tracking-widest font-bold">SYSTEM MANUAL // DOCS_V1.0</span>
        </div>
        <h1 className="font-display text-2xl md:text-3xl text-white uppercase tracking-wider">
          GameForge AI Documentation
        </h1>
        <p className="font-mono text-xs sm:text-sm text-on-surface-variant max-w-3xl leading-relaxed">
          Comprehensive architecture guide for AI-driven game discovery, natural logic prototyping, deterministic schema validation, and the browser-based Phaser 2D execution runtime.
        </p>
      </header>

      {/* Grid of Documentation Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Section 1: Platform Overview */}
        <section className="bg-terminal-bg border border-primary/30 rounded-lg p-6 space-y-3 shadow-xl glow-box-cyan flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-primary font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">rocket_launch</span>
              <span>1. Platform Overview</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Discovery & Natural Logic Prototyping</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              GameForge AI is a modular game creation and discovery platform. It transforms natural language game concepts into structured, playable 2D browser games while simultaneously providing vector-based semantic matching against an offline catalog of thousands of titles.
            </p>
          </div>
          <div className="pt-2 border-t border-primary/20 text-[11px] font-mono text-primary/80">
            Pipeline: Natural Language → Intent Spec → GameDSL → Schema Validation → Phaser Canvas
          </div>
        </section>

        {/* Section 2: Multi-Signal Discovery */}
        <section className="bg-terminal-bg border border-secondary/30 rounded-lg p-6 space-y-3 shadow-xl glow-box-magenta flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-secondary font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">search_insights</span>
              <span>2. Multi-Signal Discovery</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Semantic Catalog Matching</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              Discovery utilizes dense vector embeddings generated by SentenceTransformers paired with high-performance FAISS indexing. It processes complex search prompts with support for negative avoidance filters (e.g. "no horror"), temporary session tuning, and diversity reranking.
            </p>
          </div>
          <div className="pt-2 border-t border-secondary/20 text-[11px] font-mono text-secondary/80">
            Features: Semantic Embeddings • Negative Filters • Grounded Explanations • Comparison Matrix
          </div>
        </section>

        {/* Section 3: Natural Logic Builder */}
        <section className="bg-terminal-bg border border-tertiary/30 rounded-lg p-6 space-y-3 shadow-xl glow-box-amber flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-tertiary font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">tune</span>
              <span>3. Natural Logic Builder</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Configurable Game Architectures</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              The Builder interface allows creators to configure key mechanics before synthesis. Support spans Linear Arena topologies, Multi-Level sequential Campaigns, and generalized Open-World environments with vehicle traversal and district activities.
            </p>
          </div>
          <div className="pt-2 border-t border-tertiary/20 text-[11px] font-mono text-tertiary/80">
            Topologies: Linear Arena (1 Level) • Campaign (2–5 Levels) • Open World (Districts & Vehicles)
          </div>
        </section>

        {/* Section 4: Game DNA & Creator Progression */}
        <section className="bg-terminal-bg border border-emerald-500/30 rounded-lg p-6 space-y-3 shadow-xl flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-emerald-400 font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">genetics</span>
              <span>4. Game DNA & Progression</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Behavioral Calibration & XP</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              The Game DNA engine models user playstyle preferences across genres, mechanics, and avoidances. User actions—such as building prototypes, completing playtests, and curating discoveries—earn server-authoritative Creator XP and unlock progression milestone badges.
            </p>
          </div>
          <div className="pt-2 border-t border-emerald-500/20 text-[11px] font-mono text-emerald-400/80">
            Systems: Preference Vectors • Exploration XP • Builder Milestones • Archetype Calibration
          </div>
        </section>

        {/* Section 5: Phaser 2D Runtime */}
        <section className="bg-terminal-bg border border-primary/30 rounded-lg p-6 space-y-3 shadow-xl flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-primary font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">sports_esports</span>
              <span>5. Deterministic Phaser Runtime</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Strict Schema Validation & Safety</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              AI-generated prototypes are compiled strictly to GameDSL specifications and validated with Pydantic schemas before reaching the client. The Phaser runtime executes validated entities, weapons, objectives, and world rules safely in Canvas/WebGL with zero arbitrary code execution.
            </p>
          </div>
          <div className="pt-2 border-t border-primary/20 text-[11px] font-mono text-primary/80">
            Safety Boundary: Schema Validated JSON → Phaser Scene Loader → Local Canvas Execution
          </div>
        </section>

        {/* Section 6: Playtest Telemetry & Remixing */}
        <section className="bg-terminal-bg border border-secondary/30 rounded-lg p-6 space-y-3 shadow-xl flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-secondary font-bold font-mono text-xs uppercase">
              <span className="material-symbols-outlined text-base">auto_fix_high</span>
              <span>6. Telemetry & Intent Remix</span>
            </div>
            <h2 className="font-display text-lg text-white uppercase">Automated Critique & Lineage</h2>
            <p className="font-body text-xs text-on-surface-variant leading-relaxed">
              During prototype gameplay, the runtime gathers telemetry (shots fired, accuracy, damage taken, time elapsed) to formulate design critique. Creators can trigger one-click parameter remixes (e.g. "Increase Combat", "Faster Pace", "Add Levels") to iterate with complete version history.
            </p>
          </div>
          <div className="pt-2 border-t border-secondary/20 text-[11px] font-mono text-secondary/80">
            Iteration: In-Browser Telemetry → AI Critique → Parameter Remix → Version Lineage
          </div>
        </section>
      </div>

      {/* Section 7: Quickstart Walkthrough */}
      <section className="bg-surface-container-low border border-primary/40 rounded-lg p-6 sm:p-8 space-y-4 shadow-2xl">
        <h2 className="font-display text-xl text-white uppercase tracking-wider flex items-center gap-2">
          <span className="material-symbols-outlined text-primary">navigation</span>
          Quickstart Workflow
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
          <div className="p-4 bg-terminal-bg border border-outline-variant/50 rounded space-y-2">
            <span className="font-mono text-primary text-xs font-bold uppercase">Step 1 // Discover</span>
            <p className="font-body text-xs text-on-surface-variant">
              Search natural language ideas on the homepage to find inspiring games from our indexed catalog.
            </p>
          </div>
          <div className="p-4 bg-terminal-bg border border-outline-variant/50 rounded space-y-2">
            <span className="font-mono text-secondary text-xs font-bold uppercase">Step 2 // Configure</span>
            <p className="font-body text-xs text-on-surface-variant">
              Open the Builder to customize world architecture, visual density, physics, and gameplay modules.
            </p>
          </div>
          <div className="p-4 bg-terminal-bg border border-outline-variant/50 rounded space-y-2">
            <span className="font-mono text-emerald-400 text-xs font-bold uppercase">Step 3 // Play & Remix</span>
            <p className="font-body text-xs text-on-surface-variant">
              Compile your scene, launch the Phaser prototype, review telemetry critiques, and remix mechanics.
            </p>
          </div>
        </div>

        <div className="pt-4 flex flex-wrap gap-4 items-center">
          <Link
            to="/build"
            className="px-6 py-2.5 bg-primary text-on-primary font-mono text-xs font-bold uppercase rounded btn-interactive energy-sweep glow-cyan"
          >
            Launch Builder
          </Link>
          <Link
            to="/api-access"
            className="px-6 py-2.5 border border-primary/50 text-primary hover:bg-primary/10 font-mono text-xs font-bold uppercase rounded btn-interactive"
          >
            Explore API Access →
          </Link>
        </div>
      </section>
    </div>
  );
};

export default DocumentationPage;
