"""create build_jobs and build_logs tables

Revision ID: 1fe395775e52
Revises: 57a6f0ac8836
Create Date: 2026-08-16 18:47:00.414560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe395775e52'
down_revision: Union[str, Sequence[str], None] = '57a6f0ac8836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('art_density', sa.Integer(), nullable=False),
    sa.Column('physics', sa.Integer(), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_jobs_id'), 'build_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_build_jobs_project_id'), 'build_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_build_jobs_status'), 'build_jobs', ['status'], unique=False)
    op.create_table('build_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_logs_build_id'), 'build_logs', ['build_id'], unique=False)
    op.create_index('ix_build_logs_build_id_sequence', 'build_logs', ['build_id', 'sequence_number'], unique=True)
    op.create_index(op.f('ix_build_logs_id'), 'build_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_logs_id'), table_name='build_logs')
    op.drop_index('ix_build_logs_build_id_sequence', table_name='build_logs')
    op.drop_index(op.f('ix_build_logs_build_id'), table_name='build_logs')
    op.drop_table('build_logs')
    op.drop_index(op.f('ix_build_jobs_status'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_project_id'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_id'), table_name='build_jobs')
    op.drop_table('build_jobs')
    # ### end Alembic commands ###
