"""add game_dsl column to build_jobs table

Revision ID: efcb82ffe8c4
Revises: 1fe395775e52
Create Date: 2026-08-16 19:26:14.063463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcb82ffe8c4'
down_revision: Union[str, Sequence[str], None] = '1fe395775e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_jobs', sa.Column('game_dsl', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_jobs', 'game_dsl')
    # ### end Alembic commands ###
