import json
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union
from pydantic import ValidationError

from app.generation.dsl_models import GameDSL
from app.schemas.design_spec import HEX_COLOR_REGEX

VALID_ENTITY_TYPES = {"enemy", "collectible", "obstacle", "platform", "hazard"}
VALID_BEHAVIORS = {"patrol", "chase", "stationary", "bounce", "float", "flee", "guard", "ranged_attack"}
VALID_TRIGGERS = {
    "on_collect", "on_collide_enemy", "on_reach_goal", "on_score_target",
    "on_time_limit", "on_player_death", "on_wave_start", "on_dash",
    "on_hazard_touch", "on_enemy_defeat", "on_checkpoint", "on_powerup_expire",
}
VALID_ACTIONS = {
    "add_score", "damage_player", "heal_player", "win_game", "lose_game",
    "spawn_entity", "speed_boost", "trigger_screen_shake", "spawn_wave",
    "grant_powerup", "activate_checkpoint", "spawn_particles", "knockback_target",
}


def _normalize_entity(ent: Dict[str, Any], default_id: str) -> Dict[str, Any]:
    if not isinstance(ent, dict):
        return ent

    # 1. ID
    if "id" not in ent or not str(ent["id"]).strip():
        ent["id"] = default_id
    else:
        ent["id"] = str(ent["id"]).strip()

    # 2. Type mapping & normalization
    if "type" in ent and isinstance(ent["type"], str):
        raw_type = ent["type"].lower().strip()
        if raw_type not in VALID_ENTITY_TYPES:
            if any(w in raw_type for w in ("coin", "gem", "item", "powerup", "star", "chest", "goal", "orb", "loot", "pickup", "key", "crystal", "fuel", "point")):
                ent["type"] = "collectible"
            elif any(w in raw_type for w in ("boss", "monster", "drone", "creature", "mob", "alien", "bot", "zombie", "turret", "soldier", "enemy", "bad_guy")):
                ent["type"] = "enemy"
                if "boss" in raw_type:
                    ent["is_boss"] = True
            elif any(w in raw_type for w in ("wall", "block", "rock", "barrier", "crate", "tree", "structure", "pillar", "box", "obstacle")):
                ent["type"] = "obstacle"
            elif any(w in raw_type for w in ("floor", "ground", "ledge", "bridge", "platform")):
                ent["type"] = "platform"
            elif any(w in raw_type for w in ("lava", "spike", "fire", "laser", "acid", "pit", "saw", "mine", "hazard", "trap")):
                ent["type"] = "hazard"
            elif ent.get("points", 0) > 0 or "score" in raw_type:
                ent["type"] = "collectible"
            elif ent.get("damage", 0) > 0:
                ent["type"] = "enemy"

    # 3. Position and Dimensions (clamp oversized widths/heights > 500 generated by LLM)
    if "width" in ent:
        try:
            w_val = int(float(ent["width"]))
            if w_val > 500:
                ent["width"] = 500
        except (ValueError, TypeError):
            pass

    if "height" in ent:
        try:
            h_val = int(float(ent["height"]))
            if h_val > 500:
                ent["height"] = 500
        except (ValueError, TypeError):
            pass

    # 4. Behavior
    if "behavior" in ent and isinstance(ent["behavior"], str):
        raw_behavior = ent["behavior"].lower().strip()
        if raw_behavior not in VALID_BEHAVIORS:
            if any(w in raw_behavior for w in ("shoot", "range", "fire", "gun", "laser", "projectile")):
                ent["behavior"] = "ranged_attack"
            elif any(w in raw_behavior for w in ("chase", "follow", "hunt", "pursue", "aggro", "seek")):
                ent["behavior"] = "chase"
            elif any(w in raw_behavior for w in ("static", "idle", "none", "stay", "fixed", "still", "stand", "stop")):
                ent["behavior"] = "stationary"
            elif any(w in raw_behavior for w in ("bounce", "rebound", "pong")):
                ent["behavior"] = "bounce"
            elif any(w in raw_behavior for w in ("float", "hover", "fly", "glide", "sine")):
                ent["behavior"] = "float"
            elif any(w in raw_behavior for w in ("flee", "run", "escape", "retreat", "avoid")):
                ent["behavior"] = "flee"
            elif any(w in raw_behavior for w in ("guard", "defend", "sentry", "protect", "zone")):
                ent["behavior"] = "guard"
            elif ent.get("type") in ("obstacle", "platform", "collectible", "hazard"):
                ent["behavior"] = "stationary"

    # 5. Combat & Vitality parameters
    if ent.get("is_boss") and "health" in ent:
        try:
            h_val = int(float(ent["health"]))
            if h_val < 150:
                ent["health"] = 200
        except (ValueError, TypeError):
            ent["health"] = 200

    if ent.get("behavior") != "ranged_attack" and "telegraph_ms" in ent:
        ent["telegraph_ms"] = 0

    return ent


def _normalize_rule(rule: Dict[str, Any], default_id: str) -> Dict[str, Any]:
    if not isinstance(rule, dict):
        return rule

    if "id" not in rule or not str(rule["id"]).strip():
        rule["id"] = default_id
    else:
        rule["id"] = str(rule["id"]).strip()

    # Trigger
    trig = rule.get("trigger")
    if isinstance(trig, dict):
        trig = trig.get("type", "on_collide_enemy")
    if isinstance(trig, str):
        trig_str = trig.lower().strip()
        if trig_str not in VALID_TRIGGERS:
            if "collect" in trig_str or "pickup" in trig_str or "item" in trig_str:
                trig_str = "on_collect"
            elif "collide" in trig_str or "enemy" in trig_str or "hit" in trig_str:
                trig_str = "on_collide_enemy"
            elif "goal" in trig_str or "reach" in trig_str or "finish" in trig_str:
                trig_str = "on_reach_goal"
            elif "score" in trig_str:
                trig_str = "on_score_target"
            elif "time" in trig_str:
                trig_str = "on_time_limit"
            elif "death" in trig_str or "die" in trig_str:
                trig_str = "on_player_death"
            elif "hazard" in trig_str or "spike" in trig_str or "lava" in trig_str:
                trig_str = "on_hazard_touch"
            elif "defeat" in trig_str or "kill" in trig_str:
                trig_str = "on_enemy_defeat"
            elif "dash" in trig_str:
                trig_str = "on_dash"
        rule["trigger"] = trig_str

    # Action
    act = rule.get("action")
    params = dict(rule.get("params") or {}) if isinstance(rule.get("params"), dict) else {}
    if isinstance(act, dict):
        for k, v in act.items():
            if k != "type" and k not in params:
                params[k] = v
        act = act.get("type", "damage_player")
    if isinstance(act, str):
        act_str = act.lower().strip()
        if act_str not in VALID_ACTIONS:
            if "score" in act_str or "point" in act_str:
                act_str = "add_score"
                if "points" not in params and "score" in params:
                    params["points"] = params.pop("score")
                elif "points" not in params and "amount" not in params:
                    params["amount"] = 50
            elif "win" in act_str or "victory" in act_str:
                act_str = "win_game"
            elif "lose" in act_str or "game_over" in act_str or "defeat" in act_str:
                act_str = "lose_game"
            elif "heal" in act_str or "health" in act_str:
                act_str = "heal_player"
            elif "damage" in act_str or "hurt" in act_str:
                act_str = "damage_player"
            elif "wave" in act_str:
                act_str = "spawn_wave"
            elif "boost" in act_str or "speed" in act_str:
                act_str = "speed_boost"
        rule["action"] = act_str
    rule["params"] = params

    return rule


@dataclass
class ValidationResult:
    """Machine-readable result of Game DSL validation."""
    is_valid: bool
    dsl: Optional[GameDSL] = None
    errors: List[str] = field(default_factory=list)
    raw_data: Optional[Dict[str, Any]] = None

    def get_error_summary(self) -> str:
        """Formatted bullet points of errors for repair prompts."""
        if not self.errors:
            return "No errors."
        return "\n".join(f"- {err}" for err in self.errors)


def validate_game_dsl(data: Union[str, Dict[str, Any]]) -> ValidationResult:
    """
    Validate candidate JSON or dictionary against GameDSL schema.
    
    Returns machine-readable ValidationResult suitable for bounded repair.
    """
    raw_dict: Dict[str, Any]
    if isinstance(data, str):
        try:
            raw_dict = json.loads(data)
        except json.JSONDecodeError as e:
            return ValidationResult(
                is_valid=False,
                errors=[f"Invalid JSON format: {str(e)}"],
                raw_data=None,
            )
    elif isinstance(data, dict):
        raw_dict = dict(data)
    else:
        return ValidationResult(
            is_valid=False,
            errors=[f"Expected dict or JSON string, received {type(data).__name__}"],
            raw_data=None,
        )

    # Safe deterministic structural pre-normalization
    normalized = dict(raw_dict)
    if "schema_version" not in normalized:
        normalized["schema_version"] = "2.0"

    # Normalize metadata
    if "metadata" not in normalized or not isinstance(normalized["metadata"], dict):
        normalized["metadata"] = {}
    else:
        normalized["metadata"] = dict(normalized["metadata"])

    for field_name in ("title", "genre", "description", "archetype"):
        if field_name in normalized and field_name not in normalized["metadata"]:
            normalized["metadata"][field_name] = normalized.pop(field_name)
        elif field_name in normalized:
            normalized.pop(field_name, None)

    # Normalize world.theme
    if "world" in normalized and isinstance(normalized["world"], dict):
        normalized["world"] = dict(normalized["world"])
        if "theme" in normalized and "theme" not in normalized["world"]:
            normalized["world"]["theme"] = normalized.pop("theme")
        elif "theme" in normalized:
            normalized.pop("theme", None)

    # Normalize player
    if "player" in normalized and isinstance(normalized["player"], dict):
        normalized["player"] = dict(normalized["player"])

    # Normalize rules
    if "rules" in normalized and isinstance(normalized["rules"], list):
        for idx, rule in enumerate(normalized["rules"]):
            if isinstance(rule, dict):
                normalized["rules"][idx] = _normalize_rule(rule, f"rule_{idx + 1}")

    # Normalize entities
    if "entities" in normalized and isinstance(normalized["entities"], list):
        for idx, ent in enumerate(normalized["entities"]):
            if isinstance(ent, dict):
                normalized["entities"][idx] = _normalize_entity(ent, f"entity_{idx + 1}")

    # Normalize levels
    if "levels" in normalized and isinstance(normalized["levels"], list):
        for idx, lvl in enumerate(normalized["levels"]):
            if isinstance(lvl, dict):
                # Extract or derive level_number
                raw_num = lvl.get("level_number", lvl.get("level_id", lvl.get("id", lvl.get("stage_number", lvl.get("stage", idx + 1)))))
                if isinstance(raw_num, int):
                    lvl["level_number"] = max(1, min(10, raw_num))
                elif isinstance(raw_num, str):
                    digits = re.findall(r"\d+", raw_num)
                    lvl["level_number"] = int(digits[0]) if digits else (idx + 1)
                else:
                    lvl["level_number"] = idx + 1

                # Extract or derive title
                if "title" not in lvl or not isinstance(lvl.get("title"), str) or not lvl["title"].strip():
                    lvl["title"] = lvl.get("name", f"Stage {lvl['level_number']}")

                # Clean up non-schema / legacy fields on LevelDef
                lvl.pop("level_id", None)
                lvl.pop("id", None)
                lvl.pop("stage_number", None)
                lvl.pop("stage", None)
                lvl.pop("name", None)
                lvl.pop("stage_id", None)

                # Objective normalization
                if "objective" in lvl:
                    if isinstance(lvl["objective"], str):
                        lvl["objective"] = {"description": lvl["objective"]}
                    elif isinstance(lvl["objective"], dict):
                        obj = lvl["objective"]
                        valid_types = {"collect_all", "defeat_all", "reach_exit", "survive_time", "score_target"}
                        if "type" in obj and obj["type"] not in valid_types:
                            obj["type"] = "collect_all"

                if "entities" in lvl and isinstance(lvl["entities"], list):
                    for e_idx, ent in enumerate(lvl["entities"]):
                        if isinstance(ent, dict):
                            lvl["entities"][e_idx] = _normalize_entity(ent, f"lvl{lvl['level_number']}_ent_{e_idx+1}")

                if "rules" in lvl and isinstance(lvl["rules"], list):
                    for r_idx, rule in enumerate(lvl["rules"]):
                        if isinstance(rule, dict):
                            lvl["rules"][r_idx] = _normalize_rule(rule, f"lvl{lvl['level_number']}_rule_{r_idx+1}")

    # Bi-directional sync between top-level entities/rules and levels[0]
    if "levels" in normalized and isinstance(normalized["levels"], list) and normalized["levels"]:
        first_lvl = normalized["levels"][0]
        if isinstance(first_lvl, dict):
            # Sync entities
            if ("entities" not in normalized or not normalized["entities"]) and first_lvl.get("entities"):
                normalized["entities"] = [dict(e) for e in first_lvl["entities"] if isinstance(e, dict)]
            elif normalized.get("entities") and ("entities" not in first_lvl or not first_lvl.get("entities")):
                first_lvl["entities"] = [dict(e) for e in normalized["entities"] if isinstance(e, dict)]

            # Sync rules
            if ("rules" not in normalized or not normalized["rules"]) and first_lvl.get("rules"):
                normalized["rules"] = [dict(r) for r in first_lvl["rules"] if isinstance(r, dict)]
            elif normalized.get("rules") and ("rules" not in first_lvl or not first_lvl.get("rules")):
                first_lvl["rules"] = [dict(r) for r in normalized["rules"] if isinstance(r, dict)]

    # Archetype minimum entity auto-remediation across all entities
    meta_archetype = normalized.get("metadata", {}).get("archetype", "survival")
    curr_entities = normalized.get("entities", [])
    if not isinstance(curr_entities, list):
        curr_entities = []
        normalized["entities"] = curr_entities

    all_entities = list(curr_entities)
    if "levels" in normalized and isinstance(normalized["levels"], list):
        for lvl in normalized["levels"]:
            if isinstance(lvl, dict) and isinstance(lvl.get("entities"), list):
                all_entities.extend(lvl["entities"])

    has_coll = any(isinstance(e, dict) and e.get("type") == "collectible" for e in all_entities)
    has_enm = any(isinstance(e, dict) and e.get("type") == "enemy" for e in all_entities)

    if meta_archetype == "collector" and not has_coll:
        coll_item = {
            "id": "collectible_core_1",
            "type": "collectible",
            "x": 300,
            "y": 250,
            "width": 24,
            "height": 24,
            "points": 100,
            "color": "#ffea00",
            "behavior": "stationary",
        }
        curr_entities.append(dict(coll_item))
        normalized["entities"] = curr_entities
        if "levels" in normalized and isinstance(normalized["levels"], list) and normalized["levels"]:
            if isinstance(normalized["levels"][0], dict):
                normalized["levels"][0].setdefault("entities", []).append(dict(coll_item))

    elif meta_archetype in ("survival", "shooter", "arena") and not has_enm:
        enm_item = {
            "id": "enemy_drone_1",
            "type": "enemy",
            "x": 600,
            "y": 200,
            "width": 28,
            "height": 28,
            "speed": 100,
            "health": 20,
            "damage": 15,
            "color": "#ff0055",
            "behavior": "patrol",
            "patrol_radius": 150,
        }
        curr_entities.append(dict(enm_item))
        normalized["entities"] = curr_entities
        if "levels" in normalized and isinstance(normalized["levels"], list) and normalized["levels"]:
            if isinstance(normalized["levels"][0], dict):
                normalized["levels"][0].setdefault("entities", []).append(dict(enm_item))

    # Ensure at least 1 rule exists
    if not normalized.get("rules"):
        if meta_archetype == "collector":
            normalized["rules"] = [{"id": "rule_collect_score", "trigger": "on_collect", "action": "add_score", "params": {"points": 100}}]
        else:
            normalized["rules"] = [{"id": "rule_enemy_damage", "trigger": "on_collide_enemy", "action": "damage_player", "params": {"damage": 15}}]

    # Normalize Open World if present or world_mode is open_world
    if normalized.get("open_world") or normalized.get("world", {}).get("world_mode") == "open_world":
        from app.generation.open_world_models import SUPPORTED_ACTOR_BEHAVIORS
        from app.generation.reachability import ReachabilityValidator

        ow = dict(normalized.get("open_world") or {})
        normalized["world"] = normalized.get("world") or {}
        normalized["world"]["world_mode"] = "open_world"

        # 1. Regions (2 - 6)
        regions = list(ow.get("regions") or [])
        if len(regions) < 2:
            regions = [
                {
                    "id": "reg_district_a",
                    "name": "District A (Core)",
                    "theme": normalized["world"].get("theme", "cyberpunk"),
                    "width": 1600,
                    "height": 1200,
                    "danger_level": 1,
                    "traversal_connections": ["reg_district_b"],
                },
                {
                    "id": "reg_district_b",
                    "name": "District B (Outskirts)",
                    "theme": "wasteland" if normalized["world"].get("theme") != "wasteland" else "colony",
                    "width": 1600,
                    "height": 1200,
                    "danger_level": 3,
                    "traversal_connections": ["reg_district_a"],
                },
            ]
        elif len(regions) > 6:
            regions = regions[:6]

        reg_ids = []
        for r_idx, reg in enumerate(regions):
            if isinstance(reg, dict):
                r_id = reg.get("id") or f"reg_{r_idx + 1}"
                reg["id"] = str(r_id).strip()
                reg_ids.append(reg["id"])
                reg["name"] = reg.get("name") or f"Region {r_idx + 1}"
                reg["theme"] = reg.get("theme") or normalized["world"].get("theme", "cyberpunk")
                reg["width"] = max(400, min(3840, int(reg.get("width", 1600))))
                reg["height"] = max(300, min(2160, int(reg.get("height", 1200))))
                reg["danger_level"] = max(1, min(10, int(reg.get("danger_level", 1))))
        ow["regions"] = regions

        # 2. Connections & Graph Reachability
        connections = list(ow.get("connections") or [])
        if len(connections) > 15:
            connections = connections[:15]
        _, repaired_conns = ReachabilityValidator.validate_open_world_connectivity(regions, connections)
        ow["connections"] = repaired_conns

        # 3. Factions (1 - 5)
        factions = list(ow.get("factions") or [])
        if not factions:
            factions = [
                {
                    "id": "faction_allied",
                    "name": "Civilian Syndicate",
                    "initial_reputation": 20,
                    "color": "#00f0ff",
                },
                {
                    "id": "faction_rival",
                    "name": "Security Enforcers",
                    "initial_reputation": -10,
                    "color": "#ff0055",
                },
            ]
        elif len(factions) > 5:
            factions = factions[:5]
        fac_ids = {f.get("id") for f in factions if isinstance(f, dict)}
        ow["factions"] = factions

        # 4. POIs (3 - 25)
        pois = list(ow.get("pois") or [])
        if len(pois) < 3:
            for p_i in range(len(pois), 3):
                target_reg = reg_ids[p_i % len(reg_ids)]
                pois.append({
                    "id": f"poi_station_{p_i+1}",
                    "name": f"Outpost Terminal {p_i+1}",
                    "type": "terminal" if p_i % 2 == 0 else "garage",
                    "region_id": target_reg,
                    "x": 200 + (p_i * 300),
                    "y": 200 + (p_i * 200),
                })
        elif len(pois) > 25:
            pois = pois[:25]

        for p_idx, poi in enumerate(pois):
            if isinstance(poi, dict):
                poi["id"] = str(poi.get("id") or f"poi_{p_idx + 1}").strip()
                if poi.get("region_id") not in reg_ids:
                    poi["region_id"] = reg_ids[0]
                poi["name"] = poi.get("name") or f"POI {p_idx + 1}"
                poi["x"] = max(0, min(3840, int(poi.get("x", 200))))
                poi["y"] = max(0, min(2160, int(poi.get("y", 200))))
        ow["pois"] = pois

        # 5. Vehicles (1 - 10)
        vehicles = list(ow.get("vehicles") or [])
        if not vehicles:
            vehicles = [
                {
                    "id": "veh_speeder_1",
                    "name": "Urban Cruiser",
                    "type": "car",
                    "region_id": reg_ids[0],
                    "x": 350,
                    "y": 300,
                    "max_speed": 500,
                    "acceleration": 400,
                    "handling": 2.5,
                    "health": 250,
                    "color": "#00ffff",
                }
            ]
        elif len(vehicles) > 10:
            vehicles = vehicles[:10]

        for v_idx, veh in enumerate(vehicles):
            if isinstance(veh, dict):
                veh["id"] = str(veh.get("id") or f"veh_{v_idx + 1}").strip()
                if veh.get("region_id") not in reg_ids:
                    veh["region_id"] = reg_ids[0]
                veh["name"] = veh.get("name") or f"Vehicle {v_idx + 1}"
                veh["x"] = max(0, min(3840, int(veh.get("x", 300))))
                veh["y"] = max(0, min(2160, int(veh.get("y", 300))))
        ow["vehicles"] = vehicles

        # 6. Activities (2 - 15)
        activities = list(ow.get("activities") or [])
        if len(activities) < 2:
            activities = [
                {
                    "id": "act_delivery_1",
                    "title": "Supply Run",
                    "description": "Transport essential supplies across districts to the secure terminal.",
                    "type": "delivery",
                    "region_id": reg_ids[0],
                    "status": "available",
                    "rewards": {"score": 200, "credits": 100},
                },
                {
                    "id": "act_recon_2",
                    "title": "Sector Recon",
                    "description": "Investigate anomalous energy signatures in the outer zone.",
                    "type": "investigation",
                    "region_id": reg_ids[1] if len(reg_ids) > 1 else reg_ids[0],
                    "status": "available",
                    "rewards": {"score": 300, "credits": 150},
                },
            ]
        elif len(activities) > 15:
            activities = activities[:15]

        has_available = False
        for a_idx, act in enumerate(activities):
            if isinstance(act, dict):
                act["id"] = str(act.get("id") or f"act_{a_idx + 1}").strip()
                act["title"] = act.get("title") or f"Activity {a_idx + 1}"
                act["description"] = act.get("description") or "Complete the objective."
                if act.get("region_id") and act["region_id"] not in reg_ids:
                    act["region_id"] = reg_ids[0]
                if act.get("status") == "available":
                    has_available = True
        if not has_available and activities:
            activities[0]["status"] = "available"
        ow["activities"] = activities

        # 7. Actors (<= 50)
        actors = list(ow.get("actors") or [])
        if len(actors) > 50:
            actors = actors[:50]

        for act_idx, actor in enumerate(actors):
            if isinstance(actor, dict):
                actor["id"] = str(actor.get("id") or f"actor_{act_idx + 1}").strip()
                actor["name"] = actor.get("name") or f"Actor {act_idx + 1}"
                if actor.get("region_id") not in reg_ids:
                    actor["region_id"] = reg_ids[0]
                if actor.get("faction_id") and actor["faction_id"] not in fac_ids:
                    actor["faction_id"] = None
                # Normalize behavior strictly against SUPPORTED_ACTOR_BEHAVIORS
                raw_beh = str(actor.get("behavior", "patrol")).lower().strip()
                if raw_beh not in SUPPORTED_ACTOR_BEHAVIORS:
                    if any(w in raw_beh for w in ("wander", "walk", "roam", "patrol")):
                        actor["behavior"] = "patrol"
                    elif any(w in raw_beh for w in ("chase", "hunt", "attack")):
                        actor["behavior"] = "chase"
                    elif any(w in raw_beh for w in ("shoot", "fire", "range")):
                        actor["behavior"] = "ranged_attack"
                    elif any(w in raw_beh for w in ("guard", "stand", "sentry")):
                        actor["behavior"] = "guard"
                    elif any(w in raw_beh for w in ("flee", "run", "scared")):
                        actor["behavior"] = "flee"
                    else:
                        actor["behavior"] = "patrol"
                actor["x"] = max(0, min(3840, int(actor.get("x", 400))))
                actor["y"] = max(0, min(2160, int(actor.get("y", 400))))
        ow["actors"] = actors

        # 8. Threat System
        ts = dict(ow.get("threat_system") or {})
        if not ts:
            ts = {
                "name": "Security Alert",
                "current_level": 0,
                "max_level": 5,
                "decay_rate_per_sec": 0.05,
            }
        ow["threat_system"] = ts

        # 9. Time System
        tm = dict(ow.get("time_system") or {})
        if not tm:
            tm = {"start_hour": 8, "time_scale": 60.0, "day_night_cycle": True}
        ow["time_system"] = tm

        normalized["open_world"] = ow

    try:
        validated_dsl = GameDSL.model_validate(normalized)
        return ValidationResult(
            is_valid=True,
            dsl=validated_dsl,
            errors=[],
            raw_data=normalized,
        )
    except ValidationError as exc:
        formatted_errors: List[str] = []
        for err in exc.errors():
            loc = " -> ".join(str(l) for l in err.get("loc", []))
            msg = err.get("msg", "Validation error")
            formatted_errors.append(f"Field '{loc}': {msg}")

        return ValidationResult(
            is_valid=False,
            dsl=None,
            errors=formatted_errors,
            raw_data=raw_dict,
        )
    except ValueError as val_err:
        return ValidationResult(
            is_valid=False,
            dsl=None,
            errors=[str(val_err)],
            raw_data=raw_dict,
        )
